### ISSUE TITLE
Chronyd restart

### ISSUE THREAD

**Issue by branic** [ManageIQ/linux_admin#158]
When adding NTP servers in linux_admin/lib/linux_admin/chrony.rb chronyd should also restarted.

As it currently stands when the add_servers method is called to update the list of servers the service is not restarted. Thus a user needs to manually restart chronyd for the changes to take effect.

**Comment by Fryguy** [comment]
@carbonin Does this affect ManageIQ as well?

**Comment by Fryguy** [comment]
Either that or a "restart if already started" or something.
