### ISSUE TITLE
LinuxAdmin::Disk.local returns non-local disks in Docker container environment

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/linux_admin#159]
In Docker container, LinuxAdmin::Disk.local returns:

```
irb(main):001:0> LinuxAdmin::Disk.local
=> [#<LinuxAdmin::Disk:0x00000008fcfb40 @path="/dev/sdb">, #<LinuxAdmin::Disk:0x00000008fcfac8 @path="/dev/sda">, #<LinuxAdmin::Disk:0x00000008fcfa28 @path="/dev/hdd">, #<LinuxAdmin::Disk:0x00000008fcf960 @path="/dev/hdc">, #<LinuxAdmin::Disk:0x00000008fcf7f8 @path="/dev/hdb">, #<LinuxAdmin::Disk:0x00000008fcf758 @path="/dev/hda">]
```

while `fdisk -l` just returns /dev/sda

The extra paths reported by LinuxAdmin exists in the image, but not sure where they came from...

```
brw-rw-r-- 1 root ftp   3,  0 May 10 13:05 /dev/hda
brw-rw-r-- 1 root ftp   3, 64 May 10 13:05 /dev/hdb
brw-rw-r-- 1 root ftp  22,  0 May 10 13:05 /dev/hdc
brw-rw-r-- 1 root ftp  22, 64 May 10 13:05 /dev/hdd
brw-rw---- 1 root disk  8,  0 May 10 13:05 /dev/sda
brw-rw-r-- 1 root ftp   8, 16 May 10 13:05 /dev/sdb
```

cc @carbonin

**Comment by djberg96** [comment]
@simaishi I thought the -d option would filter those out. I'm not sure what changes have been made since this was posted. Does it still happen?

**Comment by djberg96** [comment]
@simaishi Actually, I think we can close this, since https://github.com/ManageIQ/linux_admin/pull/214 filters out anything that isn't "disk".

**Comment by simaishi** [comment]
Confirmed I don't see any extra entries with #214, closing. Thanks!
