### ISSUE TITLE
Fix Hakiri issues

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/linux_admin#179]
It's hard to review PRs because they all appear as failed.  Let's see if we can find why Hakiri fails, or just remove Hakiri. cc @carbonin

**Comment by carbonin** [comment]
I attempted this here (https://github.com/ManageIQ/linux_admin/pull/164), but we decided we needed to lock nokogiri too restrictively.

Want me to reopen a similar PR for discussion @Fryguy ?
