### ISSUE TITLE
Bump minimum nokogiri version ... again

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/linux_admin#187]
[Security issue from Hakiri](https://hakiri.io/projects/c91a7f89e057f7/stacks/4d54d4ab0538e5/builds/765d9dba180cd5/warnings/7730fa56859218)

This needs 1.7.1 as the new minimum

**Comment by carbonin** [comment]
@Fryguy Can we get the `hacktoberfest` label here for issues like this?

**Comment by Fryguy** [comment]
This was an old issue, so the 1.7.1 number was old...this should now be `"~> 1.8", ">= 1.8.1"`
