### ISSUE TITLE
Add optional :logger to LinuxAdmin.run and run!

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/linux_admin#56]
This should do the following:
1) rescue any exceptions
2) log the command, minus any params
3) log the output as info
4) log the exit code as error when non-zero
5) log standard error as error if exit code is non-zero, warn otherwise.
6) re-raise the existing exception

**Comment by carbonin** [comment]
@bdunne This can also most likely be closed as `run` and `run!` have been moved to the AwesomeSpawn gem and as of #148 will no longer be callable from `LinuxAdmin`
